# Generated by Django 3.2.6 on 2021-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210903_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
