# Generated by Django 3.2.6 on 2021-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_index_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
